name: manual-deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'dev-exemplar' 
        type: choice
        options:
        - dev
        - dev-exemplar
        - staging
        - staging-exemplar
jobs:
  beanstalk-deploy:
    name: Beanstalk Deployment
    uses: ./.github/workflows/shared-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment }}
      ecr_repository: ohm-beanstalk
    secrets:
      aws_user_account: ${{ secrets.AWS_USER_ACCOUNT }}